config/routes.rb
DraftTracker::Application.routes.draw do

  resources :ownerships
  
  root 'static_pages#home'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/live',     to: 'static_pages#live',   via: 'get'
  match '/draft',   to: 'static_pages#draft', via: 'get'
  match '/results',   to: 'static_pages#results', via: 'get'
  match '/players/undrafted',   to: 'players#undrafted', via: 'get'
  match '/players/drafted',   to: 'players#drafted', via: 'get'

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :team
	has_one :ownership

	validates :round, presence: true
	validates :pick, presence: true
	validates :team, presence: true

	scope :next, -> { where.not(id: Ownership.all.map(&:order_id)) }

end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
	belongs_to :player
	belongs_to :team
	belongs_to :order

	validates :player, presence: true
	validates :team, presence: true
	validates :order, presence: true

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_one :ownership
	has_one :team, through: :ownership

	validates :name, presence: true
	validates :position, presence: true

	scope :drafted, -> { joins(:ownership).where(players: {id: Ownership.all.map(&:player_id)}) }
	scope :undrafted, -> { where.not(id: Ownership.all.map(&:player_id)) }
	scope :by_position, -> { order('position ASC, name ASC').undrafted }
	scope :last_three, -> { drafted.order('order_id DESC').limit(3) }
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :ownerships
	has_many :players, through: :ownerships
	has_many :orders

	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :division, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController

  def create
    @ownership = Ownership.new(owner_params)
    begin
      @ownership.save
      redirect_to draft_path, notice: "#{@ownership.player.name}, #{@ownership.player.position} drafted by #{@ownership.team.name} in Round: #{@ownership.order.round} Pick: #{@ownership.order.pick}"
    #rescue if users clicks too fast and tries to add the same record twice
    rescue ActiveRecord::RecordNotUnique
      redirect_to draft_path 
    end
  end

  private
    def owner_params
      params.require(:ownership).permit(:order_id, :player_id, :team_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def undrafted
		if params[:input].nil?
			#if no input then render all undrafted players by position
			@undrafted = Player.by_position
		else
			#sort by input
			@undrafted = Player.by_position.where(position: sanitize_position_input)
		end
	end

	def drafted
		redirect_to results_path
	end

	private
		def sanitize_position_input
			#sanitize input to only allow position strings
			input = Player.all.map{ |player| player.position}
			input.include?(params[:input]) ? params[:input] : nil
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper_method :sort_column, :sort_direction

  def home
  end

  def help
  end

  def live
    @order = Order.next.first
    @team = Team.find_by_id(@order.team_id) if @order != nil
    @latest = Player.last_three
  end

  def draft
    @players = Player.undrafted.map{ |player| [player.name, player.id] }
    @order = Order.next.first
    @team = Team.find_by_id(@order.team_id) if @order != nil  
  end

  def results
    @team = Team.all.map(&:name)
    if params[:input].nil?
      #if :input is nil then it is an order all 
      @ownerships = Ownership.order(sort_column + ' ' + sort_direction)
    else
      if params[:input].length > 2
        #if input is not a number then it is a team
        team = Team.find_by_name(sanitize_input)
        @ownerships = Ownership.where(team_id: team.id)
      else
        #find all orders with :input of round
        round = Order.where(round: sanitize_input)
        @ownerships = Array.new
        round.each do |round|
          @ownerships += Ownership.where(order_id: round.id)
        end
      end    
    end
  end

  private
    def sanitize_input
      #santize input such that it is only a team name or 1-7
      input = Team.all.map(&:name)
      input+= %w[1 2 3 4 5 6 7]
      input.include?(params[:input]) ? params[:input] : nil
    end

    def sort_column 
      #sanitize params to make sure :sort is a ownership column name
      Ownership.column_names.include?(params[:sort]) ? params[:sort] : "order_id"
    end

    def sort_direction
      #sanitize params to make sure :direction is asc or desc
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title=nil)
		title ||= column.titleize
		if column == 'Name'
			sort_by = 'player_id'
		elsif column == "Team"
			sort_by = 'team_id'
		elsif column == "Round"||"Pick"
			sort_by = 'order_id'
		else
			sort_by = column
		end
		css_class = (sort_by == sort_column) ? "current #{sort_direction}" : nil
		direction = (sort_by == sort_column && sort_direction=="asc") ? "desc" : "asc"
		link_to title, {:sort => sort_by, :direction => direction}, {:class => css_class}
	end

	def sortable_by(input, title=nil)
		title ||= input.to_s.titleize
		link_to title, :input => input
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    NFL Draft Tracker by Chris Barthol
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "NFL Draft Tracker", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Players <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Undrafted Players", players_undrafted_path %></li>
              <li><%= link_to "Drafted Players", players_drafted_path %></li>
            </ul>
          </li>
          <li><%= link_to "Results", results_path %></li>
          <li><%= link_to "Live", live_path %></li>
          <li><%= link_to "Draft", draft_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NFL Draft Tracker</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> <!-- For IE -->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <!-- Render flash messages -->
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%=(name == :notice && 'success' or name == :warning && 'warning' or name == :info && 'info' or 'error')%>">

          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/ownerships/_ownership.html.erb
<div class="container">
	<section class="row">
		<div class="span2 offset1">
			<span>
				<%= ownership.player.name %>
			</span>
		</div>
		<div class="span2 center">
			<span>
				<%= ownership.player.position %>
			</span>
		</div>
		<div class="span3">
			<span>
				<%= ownership.team.name %>
			</span>
		</div>
		<div class="span1 center">
			<span>
				<%= ownership.order.round %>
			</span>
		</div>
		<div class="span1 center">
			<span>
				<%= ownership.order.pick %>
			</span>
		</div>
	</section>
</div>

app/views/players/_player.html.erb
<div class="container">
	<section class="row">
		<div class="span3 offset1">
			<span>
				<%= player.name %>
			</span>
		</div>
		<div class="span2">
			<span>
				<%= player.position %>
			</span>
		</div>
		<% if player.team.nil? %>
		<% else %>
			<div class="span3">
				<span>
					<%= player.team.name %>
				</span>
			</div>
			<div class="span1">
				<span>
					<%= player.ownership.order.round %>
				</span>
			</div>
			<div class="span1">
				<span>
					<%= player.ownership.order.pick %>
				</span>
			</div>
		<% end %>
	</section>
</div>

app/views/players/_sort_by_position.html.erb
<div class="container sort-position center">
	<section class="row">
		<div class="span2">
			<%= sortable_by "C" %>
		</div>
		<div class="span2">
			<%= sortable_by "CB" %>
		</div>
		<div class="span2">
			<%= sortable_by "DE" %>
		</div>
		<div class="span2">
			<%= sortable_by "DT" %>
		</div>
		<div class="span2">
			<%= sortable_by "FB" %>
		</div>
		<div class="span2">
			<%= sortable_by "FS" %>
		</div>
		<div class="span2">
			<%= sortable_by "ILB" %>
		</div>
		<div class="span2">
			<%= sortable_by "K" %>
		</div>
		<div class="span2">
			<%= sortable_by "LS" %>
		</div>
		<div class="span2">
			<%= sortable_by "OG" %>
		</div>
		<div class="span2">
			<%= sortable_by "OLB" %>
		</div>
		<div class="span2">
			<%= sortable_by "OT" %>
		</div>
		<div class="span2">
			<%= sortable_by "P" %>
		</div>
		<div class="span2">
			<%= sortable_by "QB" %>
		</div>
		<div class="span2">
			<%= sortable_by "RB" %>
		</div>
		<div class="span2">
			<%= sortable_by "SS" %>
		</div>
		<div class="span2">
			<%= sortable_by "TE" %>
		</div>
		<div class="span2">
			<%= sortable_by "WR" %>
		</div>
	</section>
</div>

app/views/players/drafted.html.erb
<div class="center hero-unit">
	<h1>Drafted Players</h1>
</div>
<%= render @drafted %>

app/views/players/undrafted.html.erb
<div class="center hero-unit">
	<h1>Undrafted Players</h1>
</div>
<h3>Sort by Position</h3>
<%= render partial: 'sort_by_position' %>
<h3>Players</h3>
<div class="container">
	<section class="row">
		<div class="span2 offset1">
			<span>
				<strong>Name</strong>
			</span>
		</div>
		<div class="span2 center">
			<span>
				<strong>Position</strong>
			</span>
		</div>
	</section>
</div>

<%= render @undrafted %>

app/views/shared/_draft_over.html.erb
<div class="draft-over center">
	<h1>The draft is over.</h1>
	<h3>View the <%= link_to 'Results.', results_path %></h3>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_order_info.html.erb
<div class="container order-info">
	<div class="center">
		<strong>Current Draft Selection</strong>
	</div>
	<section class="row">
		<div class="span3 offset1">
			<span>
				Round: <%= @order.round %>
			</span>
		</div>
		<div class="span2">
			<span>
				Pick: <%= @order.pick %>
			</span>
		</div>
		<div class="span6">
			<span>
				Team: <%= @team.name %>
			</span>
		</div>
	</section>
</div>

app/views/static_pages/_sort_by_round.html.erb
<div class="container">
	<section class="row">
		<div class="span1">
			<%= sortable_by 1 %>
		</div>
		<div class="span1">
			<%= sortable_by 2 %>
		</div>
		<div class="span1">
			<%= sortable_by 3 %>
		</div>
		<div class="span1">
			<%= sortable_by 4 %>
		</div>
		<div class="span1">
			<%= sortable_by 5 %>
		</div>
		<div class="span1">
			<%= sortable_by 6 %>
		</div>
		<div class="span1">
			<%= sortable_by 7 %>
		</div>
	</section>
</div>

app/views/static_pages/_sort_by_team.html.erb
<div class="container">
	<section class="row">
		<div class="span3">
			<%= sortable_by "Arizona Cardinals" %>
		</div>
		<div class="span3">
			<%= sortable_by "Atlanta Falcons" %>
		</div>
		<div class="span3">
			<%= sortable_by "Baltimore Ravens" %>
		</div>
		<div class="span3">
			<%= sortable_by "Buffalo Bills" %>
		</div>
		<div class="span3">
			<%= sortable_by "Carolina Panthers" %>
		</div>
		<div class="span3">
			<%= sortable_by "Chicago Bears" %>
		</div>
		<div class="span3">
			<%= sortable_by "Cincinnati Bengals" %>
		</div>
		<div class="span3">
			<%= sortable_by "Dallas Cowboys" %>
		</div>
		<div class="span3">
			<%= sortable_by "Denver Broncos" %>
		</div>
		<div class="span3">
			<%= sortable_by "Detroit Lions" %>
		</div>
		<div class="span3">
			<%= sortable_by "Green Bay Packers" %>
		</div>
		<div class="span3">
			<%= sortable_by "Houston Texans" %>
		</div>
		<div class="span3">
			<%= sortable_by "Indianapolis Colts" %>
		</div>
		<div class="span3">
			<%= sortable_by "Jacksonville Jaguars" %>
		</div>
		<div class="span3">
			<%= sortable_by "Kansas City Chiefs" %>
		</div>
		<div class="span3">
			<%= sortable_by "Miami Dolphins" %>
		</div>
		<div class="span3">
			<%= sortable_by "Minnesota Vikings" %>
		</div>
		<div class="span3">
			<%= sortable_by "New England Patriots" %>
		</div>
		<div class="span3">
			<%= sortable_by "New Orleans Saints" %>
		</div>
		<div class="span3">
			<%= sortable_by "New York Giants" %>
		</div>
		<div class="span3">
			<%= sortable_by "New York Jets" %>
		</div>
		<div class="span3">
			<%= sortable_by "Oakland Raiders" %>
		</div>
		<div class="span3">
			<%= sortable_by "Philadelphia Eagles" %>
		</div>
		<div class="span3">
			<%= sortable_by "Pittsburgh Steelers" %>
		</div>
		<div class="span3">
			<%= sortable_by "San Diego Chargers" %>
		</div>
		<div class="span3">
			<%= sortable_by "San Francisco 49ers" %>
		</div>
		<div class="span3">
			<%= sortable_by "Seattle Seahawks" %>
		</div>
		<div class="span3">
			<%= sortable_by "St. Louis Rams" %>
		</div>
		<div class="span3">
			<%= sortable_by "Tampa Bay Buccaneers" %>
		</div>
		<div class="span3">
			<%= sortable_by "Tennessee Titans" %>
		</div>
		<div class="span3">
			<%= sortable_by "Washington Redskins" %>
		</div>
	</section>
</div>

app/views/static_pages/draft.html.erb
<div class="center hero-unit">
	<h1>NFL Draft</h1>
</div>
<% if @order ==nil %>
<%= render partial: 'shared/draft_over' %>
<% else %>
<%= render partial: 'shared/order_info' %>

<div class="container select center">
	<%= form_for(Ownership.new) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="field">
			<%= f.label "Player" %>
		    <%= f.select :player_id, @players %>
		    <div><%= f.hidden_field :order_id, :value => @order.id %></div>
		    <div><%= f.hidden_field :team_id, :value => @team.id %></div>
		  </div>
		  <%= f.submit "Draft Player", class: "btn btn-large btn-primary" %>
	<% end %>
</div>
<% end %>

app/views/static_pages/help.html.erb
<div class="center hero-unit">
	<h1>NFL Draft Tracker Help</h1>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to the NFL Draft Tracker</h1>
</div>
<div class="container center">
	<h3>
		<p>Follow the draft:</p>
		<p>
			<%= link_to "Live!", live_path, class: "btn btn-large btn-primary" %>
		</p>
		<p>Or view the results:</p>
		<p>
			<%= link_to "Results!", results_path, class: "btn btn-large btn-primary" %>
		</p>
	</h3>
</div>

app/views/static_pages/live.html.erb
<div class="center hero-unit">
	<h1>NFL Draft Live</h1>
	<% if @order ==nil %>
		<h2> The draft is currently over. </h2>
	<% else %>
		<h2> You are viewing the Draft Tracker Live! </h2>
	<% end %>
</div>
<% if @order ==nil %>
<%= render partial: 'shared/draft_over' %>
<% else %>

<%= render partial: 'shared/order_info' %>
<% end %>

<div class="last-three">
	<h3 class="pull-left"> Last Three Draft Picks </h3>
	<section class="row bold">
		<div class="span3 offset1">
			<span>
				<strong>Name</strong>
			</span>
		</div>
		<div class="span2">
			<span>
				<strong>Position</strong>
			</span>
		</div>
		<div class="span3">
			<span>
				<strong>Team</strong>
			</span>
		</div>
		<div class="span1">
			<span>
				<strong>Round</strong>
			</span>
		</div>
		<div class="span1">
			<span>
				<strong>Pick</strong>
			</span>
		</div>
	</section>
	<%= render @latest %>
</div>

app/views/static_pages/results.html.erb
<div class="center hero-unit">
	<h1>NFL Draft Results</h1>
</div>
<h3>Sort by Team</h3>
<%= render partial: 'static_pages/sort_by_team' %>
<h3>Sort by Round</h3>
<%= render partial: 'static_pages/sort_by_round' %>
<h3>Results</h3>
<div class="container">
	<section class="row">
		<div class="span2 offset1">
			<span>
				<strong>Name</strong>
			</span>
		</div>
		<div class="span2 center">
			<span>
				<strong>Position</strong>
			</span>
		</div>
		<div class="span3">
			<span>
				<strong><%= sortable 'Team' %></strong>
			</span>
		</div>
		<div class="span1 center">
			<span>
				<strong><%= sortable 'Round' %></strong>
			</span>
		</div>
		<div class="span1 center">
			<span>
				<strong>Pick</strong>
			</span>
		</div>
	</section>
</div>
<%= render @ownerships %>